apiVersion: apps/v1
kind: Deployment
metadata:
  name: kta-quickstart-kstreams-tokenizer-counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kstreams
      component: tokenizer-counter
  template:
    metadata:
      labels:
        app: kstreams
        component: tokenizer-counter
    spec:
      # TODO: remove
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: tokenizer-counter
          # TODO: Change on new release
          image: ghcr.io/dynatrace-oss/kta-quickstart-kstreams:v0.1.0-alpha.1-dev.1
          imagePullPolicy: Always
          args: ["tokenizer-counter"]
