apiVersion: apps/v1
kind: Deployment
metadata:
  name: kta-quickstart-kstreams-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstreams
      component: producer
  template:
    metadata:
      labels:
        app: kstreams
        component: producer
    spec:
      # TODO: remove
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: producer
          # TODO: Change on new release
          image: ghcr.io/dynatrace-oss/kta-quickstart-kstreams:v0.1.0-alpha.1-dev.1
          imagePullPolicy: Always
          args: ["producer", "1000"]
