# Dependency versions
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.24.2
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.24.2
assertjVersion=3.27.3
mockServerVersion=5.15.0
# ATTENTION: Make sure that the version matches with the Operator Framework version in the Quarkus Operator SDK Extension
operatorFrameworkJunit5Version=5.1.1

# Quarkus configuration
quarkus.operator-sdk.crd.generate=true
quarkus.operator-sdk.crd.apply=true
# TODO: enable for HELM chart
quarkus.operator-sdk.helm.enabled=false
# TODO: Currently, everything needs to be deployed into default namespace. Other setups were not tested.
quarkus.kubernetes.namespace=default
quarkus.kubernetes.rbac.cluster-roles."kta-deployment-role".name=kta-deployment-role
quarkus.kubernetes.rbac.cluster-roles."kta-deployment-role".policy-rules."policy-rules".api-groups=apps
quarkus.kubernetes.rbac.cluster-roles."kta-deployment-role".policy-rules."policy-rules".resources=deployments,deployments/scale
quarkus.kubernetes.rbac.cluster-roles."kta-deployment-role".policy-rules."policy-rules".verbs=get,update,patch
quarkus.kubernetes.rbac.cluster-role-bindings."kta-deployment-role-binding".name=kta-deployment-role-binding
quarkus.kubernetes.rbac.cluster-role-bindings."kta-deployment-role-binding".role-name=kta-deployment-role
quarkus.kubernetes.rbac.cluster-role-bindings."kta-deployment-role-binding".subjects."kta".name=kta
quarkus.kubernetes.rbac.cluster-role-bindings."kta-deployment-role-binding".subjects."kta".namespace=default
quarkus.kubernetes.idempotent=true

# Fix image digest to make build reproducible
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-17@sha256:746fa1bf5c29aa3de0cf4af65e8f51bdde6e6f75753cb0e7eededca3883940a9
quarkus.jib.base-native-image=quay.io/quarkus/quarkus-micro-image@sha256:08263c65b8fc93055cd1ac62e6d63eeb612270f0e37a03bd1ab7a69b3e272a7b
